#
# Vivado (TM) v2016.3 (64-bit)
#
# project_tcl.tcl: Tcl script for re-creating project 'MatrixMultiplyEngine'
#
# Generated by Vivado on Thu Mar 16 12:57:51 PDT 2017
# IP Build 1681267 on Mon Oct 10 21:28:31 MDT 2016
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (project_tcl.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    <none>
#
# 3. The following remote source files that were added to the original project:-
#
#    "/sampa/home/gyorgym/MatrixMultiplyEngine/srcs/nRegisterChain.v"
#    "/sampa/home/gyorgym/MatrixMultiplyEngine/srcs/noOverflowMult.v"
#    "/sampa/home/gyorgym/MatrixMultiplyEngine/srcs/noOverflowAdd.v"
#    "/sampa/home/gyorgym/MatrixMultiplyEngine/srcs/clogb2.v"
#    "/sampa/home/gyorgym/MatrixMultiplyEngine/srcs/vectorSum.v"
#    "/sampa/home/gyorgym/MatrixMultiplyEngine/srcs/vectorMult.v"
#    "/sampa/home/gyorgym/MatrixMultiplyEngine/srcs/dotProduct.v"
#    "/sampa/home/gyorgym/MatrixMultiplyEngine/srcs/matrixMult.v"
#    "/sampa/home/gyorgym/MatrixMultiplyEngine/srcs/vectorSum.v"
#    "/sampa/home/gyorgym/MatrixMultiplyEngine/sim/tb/matrixMult_testbench.v"
#    "/sampa/home/gyorgym/MatrixMultiplyEngine/sim/tb/dotProduct_testbench.v"
#    "/sampa/home/gyorgym/MatrixMultiplyEngine/sim/tb/dotProduct_testbench2.v"
#    "/sampa/home/gyorgym/MatrixMultiplyEngine/sim/tb/noOverflowMult_testbench.v"
#    "/sampa/home/gyorgym/MatrixMultiplyEngine/sim/tb/parallelAdder_testbench.v"
#    "/sampa/home/gyorgym/MatrixMultiplyEngine/sim/tb/noOverflowAdd_testbench.v"
#    "/sampa/home/gyorgym/MatrixMultiplyEngine/sim/tb/nRegisterChain_testbench.v"
#    "/sampa/home/gyorgym/MatrixMultiplyEngine/sim/tb/vectorMult_testbench.v"
#    "/sampa/home/gyorgym/MatrixMultiplyEngine/sim/tb/parallelAdder4_testbench.v"
#    "/sampa/home/gyorgym/MatrixMultiplyEngine/sim/tb/vectorSum_testbench.v"
#    "/sampa/home/gyorgym/MatrixMultiplyEngine/sim/scripts/input_matrix.mif"
#    "/sampa/home/gyorgym/MatrixMultiplyEngine/sim/scripts/weight_matrix.mif"
#    "/sampa/home/gyorgym/MatrixMultiplyEngine/sim/scripts/out_matrix.mif"
#    "/sampa/home/gyorgym/MatrixMultiplyEngine/sim/wf_config/matrixMult_testbench_behav.wcfg"
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

variable script_file
set script_file "project_tcl.tcl"

# Help information for this script
proc help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < [llength $::argc]} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir" { incr i; set origin_dir [lindex $::argv $i] }
      "--help"       { help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/MatrixMultiplyEngine"]"

# Create project
create_project MatrixMultiplyEngine ./MatrixMultiplyEngine -part xc7z020clg484-1

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Reconstruct message rules
# None

# Set project properties
set obj [get_projects MatrixMultiplyEngine]
set_property "board_part" "xilinx.com:zc702:part0:1.2" $obj
set_property "default_lib" "xil_defaultlib" $obj
set_property "ip_cache_permissions" "read write" $obj
set_property "ip_output_repo" "/sampa/home/gyorgym/MatrixMultiplyEngine/MatrixMultiplyEngine.cache/ip" $obj
set_property "sim.ip.auto_export_scripts" "1" $obj
set_property "simulator_language" "Mixed" $obj
set_property "xsim.array_display_limit" "64" $obj
set_property "xsim.trace_limit" "65536" $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/srcs/nRegisterChain.v"]"\
 "[file normalize "$origin_dir/srcs/noOverflowMult.v"]"\
 "[file normalize "$origin_dir/srcs/noOverflowAdd.v"]"\
 "[file normalize "$origin_dir/srcs/clogb2.v"]"\
 "[file normalize "$origin_dir/srcs/vectorSum.v"]"\
 "[file normalize "$origin_dir/srcs/vectorMult.v"]"\
 "[file normalize "$origin_dir/srcs/dotProduct.v"]"\
 "[file normalize "$origin_dir/srcs/matrixMult.v"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property "top" "matrixMult" $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Empty (no sources present)

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
set files [list \
 "[file normalize "$origin_dir/srcs/vectorSum.v"]"\
 "[file normalize "$origin_dir/sim/tb/matrixMult_testbench.v"]"\
 "[file normalize "$origin_dir/sim/tb/dotProduct_testbench.v"]"\
 "[file normalize "$origin_dir/sim/tb/dotProduct_testbench2.v"]"\
 "[file normalize "$origin_dir/sim/tb/noOverflowMult_testbench.v"]"\
 "[file normalize "$origin_dir/sim/tb/parallelAdder_testbench.v"]"\
 "[file normalize "$origin_dir/sim/tb/noOverflowAdd_testbench.v"]"\
 "[file normalize "$origin_dir/sim/tb/nRegisterChain_testbench.v"]"\
 "[file normalize "$origin_dir/sim/tb/vectorMult_testbench.v"]"\
 "[file normalize "$origin_dir/sim/tb/parallelAdder4_testbench.v"]"\
 "[file normalize "$origin_dir/sim/tb/vectorSum_testbench.v"]"\
 "[file normalize "$origin_dir/sim/scripts/input_matrix.mif"]"\
 "[file normalize "$origin_dir/sim/scripts/weight_matrix.mif"]"\
 "[file normalize "$origin_dir/sim/scripts/out_matrix.mif"]"\
 "[file normalize "$origin_dir/sim/wf_config/matrixMult_testbench_behav.wcfg"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sim_1' fileset file properties for remote files
set file "$origin_dir/sim/scripts/input_matrix.mif"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property "file_type" "Memory Initialization Files" $file_obj

set file "$origin_dir/sim/scripts/weight_matrix.mif"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property "file_type" "Memory Initialization Files" $file_obj

set file "$origin_dir/sim/scripts/out_matrix.mif"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property "file_type" "Memory Initialization Files" $file_obj


# Set 'sim_1' fileset file properties for local files
# None

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property "runtime" "1100ns" $obj
set_property "top" "matrixMult_testbench" $obj
set_property "transport_int_delay" "0" $obj
set_property "transport_path_delay" "0" $obj
set_property "xelab.nosort" "1" $obj
set_property "xelab.unifast" "" $obj
set_property "xsim.simulate.runtime" "1100ns" $obj
set_property "xsim.view" "/sampa/home/gyorgym/MatrixMultiplyEngine/srcs/testbenches/matrixMult_testbench_behav.wcfg /sampa/home/gyorgym/MatrixMultiplyEngine/sim/wf_config/matrixMult_testbench_behav.wcfg" $obj

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
  create_run -name synth_1 -part xc7z020clg484-1 -flow {Vivado Synthesis 2016} -strategy "Vivado Synthesis Defaults" -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2016" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property "needs_refresh" "1" $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
  create_run -name impl_1 -part xc7z020clg484-1 -flow {Vivado Implementation 2016} -strategy "Vivado Implementation Defaults" -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2016" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property "steps.write_bitstream.args.readback_file" "0" $obj
set_property "steps.write_bitstream.args.verbose" "0" $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:MatrixMultiplyEngine"
